
#ifndef FORCESNLPSOLVER_CASADI_H
#define FORCESNLPSOLVER_CASADI_H

/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

int FORCESNLPsolver_objective0rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void FORCESNLPsolver_objective0rd_1_incref(void);

const casadi_int* FORCESNLPsolver_objective0rd_1_sparsity_out(casadi_int i);

int FORCESNLPsolver_objective1rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void FORCESNLPsolver_objective1rd_1_incref(void);

const casadi_int* FORCESNLPsolver_objective1rd_1_sparsity_out(casadi_int i);

int FORCESNLPsolver_dynamics0rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void FORCESNLPsolver_dynamics0rd_1_incref(void);

const casadi_int* FORCESNLPsolver_dynamics0rd_1_sparsity_out(casadi_int i);

int FORCESNLPsolver_dynamics1rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void FORCESNLPsolver_dynamics1rd_1_incref(void);

const casadi_int* FORCESNLPsolver_dynamics1rd_1_sparsity_out(casadi_int i);

int FORCESNLPsolver_objective0rd_30(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void FORCESNLPsolver_objective0rd_30_incref(void);

const casadi_int* FORCESNLPsolver_objective0rd_30_sparsity_out(casadi_int i);

int FORCESNLPsolver_objective1rd_30(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);

void FORCESNLPsolver_objective1rd_30_incref(void);

const casadi_int* FORCESNLPsolver_objective1rd_30_sparsity_out(casadi_int i);

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif
