/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FORCESNLPsolver_casadi_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[14] = {1, 7, 0, 1, 2, 3, 4, 4, 4, 4, 0, 0, 0, 0};
static const casadi_int casadi_s5[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s6[25] = {5, 7, 0, 1, 2, 3, 4, 8, 11, 15, 2, 4, 0, 1, 0, 1, 2, 3, 0, 1, 3, 0, 1, 3, 4};

/* FORCESNLPsolver_objective0rd_1:(i0[7],i1[2],i2[],i3[])->(o0) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
    a0=5.0000000000000000e-001;
    a1=4.4721359549995796e+001;
    a2=arg[0]? arg[0][2] : 0;
    a3=arg[1]? arg[1][0] : 0;
    a4=(a2-a3);
    a4=(a1*a4);
    a2=(a2-a3);
    a2=(a1*a2);
    a4=(a4*a2);
    a2=arg[0]? arg[0][3] : 0;
    a3=arg[1]? arg[1][1] : 0;
    a5=(a2-a3);
    a5=(a1*a5);
    a2=(a2-a3);
    a1=(a1*a2);
    a5=(a5*a1);
    a4=(a4+a5);
    a5=1.4142135623730950e-001;
    a1=arg[0]? arg[0][0] : 0;
    a5=(a5*a1);
    a5=casadi_sq(a5);
    a4=(a4+a5);
    a5=1.4142135623730951e+000;
    a1=arg[0]? arg[0][1] : 0;
    a5=(a5*a1);
    a5=casadi_sq(a5);
    a4=(a4+a5);
    a0=(a0*a4);
    if (res[0]!=0) res[0][0]=a0;
    return 0;
}

int FORCESNLPsolver_objective0rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f0(arg, res, iw, w, mem);
}

const casadi_int* FORCESNLPsolver_objective0rd_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s3;
        default: return 0;
    }
}

/* FORCESNLPsolver_objective1rd_1:(i0[7],i1[2],i2[],i3[])->(o0[1x7,4nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
    a0=1.4142135623730950e-001;
    a1=5.0000000000000000e-001;
    a2=arg[0]? arg[0][0] : 0;
    a2=(a0*a2);
    a2=(a2+a2);
    a2=(a1*a2);
    a0=(a0*a2);
    if (res[0]!=0) res[0][0]=a0;
    a0=1.4142135623730951e+000;
    a2=arg[0]? arg[0][1] : 0;
    a2=(a0*a2);
    a2=(a2+a2);
    a2=(a1*a2);
    a0=(a0*a2);
    if (res[0]!=0) res[0][1]=a0;
    a0=4.4721359549995796e+001;
    a2=arg[0]? arg[0][2] : 0;
    a3=arg[1]? arg[1][0] : 0;
    a4=(a2-a3);
    a4=(a0*a4);
    a4=(a1*a4);
    a4=(a0*a4);
    a2=(a2-a3);
    a2=(a0*a2);
    a2=(a1*a2);
    a2=(a0*a2);
    a4=(a4+a2);
    if (res[0]!=0) res[0][2]=a4;
    a4=arg[0]? arg[0][3] : 0;
    a2=arg[1]? arg[1][1] : 0;
    a3=(a4-a2);
    a3=(a0*a3);
    a3=(a1*a3);
    a3=(a0*a3);
    a4=(a4-a2);
    a4=(a0*a4);
    a1=(a1*a4);
    a0=(a0*a1);
    a3=(a3+a0);
    if (res[0]!=0) res[0][3]=a3;
    return 0;
}

int FORCESNLPsolver_objective1rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f1(arg, res, iw, w, mem);
}

const casadi_int* FORCESNLPsolver_objective1rd_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s4;
        default: return 0;
    }
}

/* FORCESNLPsolver_dynamics0rd_1:(i0[7],i1[2],i2[],i3[])->(o0[5]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
    a0=arg[0]? arg[0][2] : 0;
    a1=1.0000000000000001e-001;
    a2=arg[0]? arg[0][4] : 0;
    a3=arg[0]? arg[0][5] : 0;
    a4=5.0000000000000000e-001;
    a5=arg[0]? arg[0][6] : 0;
    a6=tan(a5);
    a6=(a4*a6);
    a6=atan(a6);
    a7=(a3+a6);
    a7=sin(a7);
    a7=(a2*a7);
    a7=(a1*a7);
    a0=(a0+a7);
    if (res[0]!=0) res[0][0]=a0;
    a0=arg[0]? arg[0][3] : 0;
    a7=(a3+a6);
    a7=cos(a7);
    a7=(a2*a7);
    a7=(a1*a7);
    a0=(a0+a7);
    if (res[0]!=0) res[0][1]=a0;
    a0=arg[0]? arg[0][0] : 0;
    a7=250.;
    a0=(a0/a7);
    a0=(a1*a0);
    a0=(a2+a0);
    if (res[0]!=0) res[0][2]=a0;
    a2=(a2/a4);
    a6=sin(a6);
    a2=(a2*a6);
    a2=(a1*a2);
    a3=(a3+a2);
    if (res[0]!=0) res[0][3]=a3;
    a3=arg[0]? arg[0][1] : 0;
    a1=(a1*a3);
    a5=(a5+a1);
    if (res[0]!=0) res[0][4]=a5;
    return 0;
}

int FORCESNLPsolver_dynamics0rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f2(arg, res, iw, w, mem);
}

const casadi_int* FORCESNLPsolver_dynamics0rd_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s5;
        default: return 0;
    }
}

/* FORCESNLPsolver_dynamics1rd_1:(i0[7],i1[2],i2[],i3[])->(o0[5x7,15nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8, a9;
    a0=4.0000000000000002e-004;
    if (res[0]!=0) res[0][0]=a0;
    a0=1.0000000000000001e-001;
    if (res[0]!=0) res[0][1]=a0;
    a1=1.;
    if (res[0]!=0) res[0][2]=a1;
    if (res[0]!=0) res[0][3]=a1;
    a2=arg[0]? arg[0][5] : 0;
    a3=5.0000000000000000e-001;
    a4=arg[0]? arg[0][6] : 0;
    a5=tan(a4);
    a5=(a3*a5);
    a6=atan(a5);
    a7=(a2+a6);
    a8=sin(a7);
    a8=(a0*a8);
    if (res[0]!=0) res[0][4]=a8;
    a2=(a2+a6);
    a8=cos(a2);
    a8=(a0*a8);
    if (res[0]!=0) res[0][5]=a8;
    if (res[0]!=0) res[0][6]=a1;
    a8=2.;
    a9=sin(a6);
    a8=(a8*a9);
    a8=(a0*a8);
    if (res[0]!=0) res[0][7]=a8;
    a8=arg[0]? arg[0][4] : 0;
    a7=cos(a7);
    a9=(a8*a7);
    a9=(a0*a9);
    if (res[0]!=0) res[0][8]=a9;
    a2=sin(a2);
    a9=(a8*a2);
    a9=(a0*a9);
    a9=(-a9);
    if (res[0]!=0) res[0][9]=a9;
    if (res[0]!=0) res[0][10]=a1;
    a4=cos(a4);
    a4=casadi_sq(a4);
    a4=(a3/a4);
    a5=casadi_sq(a5);
    a5=(a1+a5);
    a4=(a4/a5);
    a7=(a7*a4);
    a7=(a8*a7);
    a7=(a0*a7);
    if (res[0]!=0) res[0][11]=a7;
    a2=(a2*a4);
    a2=(a8*a2);
    a2=(a0*a2);
    a2=(-a2);
    if (res[0]!=0) res[0][12]=a2;
    a8=(a8/a3);
    a6=cos(a6);
    a6=(a6*a4);
    a8=(a8*a6);
    a0=(a0*a8);
    if (res[0]!=0) res[0][13]=a0;
    if (res[0]!=0) res[0][14]=a1;
    return 0;
}

int FORCESNLPsolver_dynamics1rd_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f3(arg, res, iw, w, mem);
}

const casadi_int* FORCESNLPsolver_dynamics1rd_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s6;
        default: return 0;
    }
}

/* FORCESNLPsolver_objective0rd_30:(i0[7],i1[2],i2[],i3[])->(o0) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
    a0=5.0000000000000000e-001;
    a1=4.4721359549995796e+001;
    a2=arg[0]? arg[0][2] : 0;
    a3=arg[1]? arg[1][0] : 0;
    a4=(a2-a3);
    a4=(a1*a4);
    a2=(a2-a3);
    a2=(a1*a2);
    a4=(a4*a2);
    a2=arg[0]? arg[0][3] : 0;
    a3=arg[1]? arg[1][1] : 0;
    a5=(a2-a3);
    a5=(a1*a5);
    a2=(a2-a3);
    a1=(a1*a2);
    a5=(a5*a1);
    a4=(a4+a5);
    a5=1.4142135623730950e-001;
    a1=arg[0]? arg[0][0] : 0;
    a5=(a5*a1);
    a5=casadi_sq(a5);
    a4=(a4+a5);
    a5=1.4142135623730951e+000;
    a1=arg[0]? arg[0][1] : 0;
    a5=(a5*a1);
    a5=casadi_sq(a5);
    a4=(a4+a5);
    a0=(a0*a4);
    if (res[0]!=0) res[0][0]=a0;
    return 0;
}

int FORCESNLPsolver_objective0rd_30(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f4(arg, res, iw, w, mem);
}

const casadi_int* FORCESNLPsolver_objective0rd_30_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s3;
        default: return 0;
    }
}

/* FORCESNLPsolver_objective1rd_30:(i0[7],i1[2],i2[],i3[])->(o0[1x7,4nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
    a0=1.4142135623730950e-001;
    a1=5.0000000000000000e-001;
    a2=arg[0]? arg[0][0] : 0;
    a2=(a0*a2);
    a2=(a2+a2);
    a2=(a1*a2);
    a0=(a0*a2);
    if (res[0]!=0) res[0][0]=a0;
    a0=1.4142135623730951e+000;
    a2=arg[0]? arg[0][1] : 0;
    a2=(a0*a2);
    a2=(a2+a2);
    a2=(a1*a2);
    a0=(a0*a2);
    if (res[0]!=0) res[0][1]=a0;
    a0=4.4721359549995796e+001;
    a2=arg[0]? arg[0][2] : 0;
    a3=arg[1]? arg[1][0] : 0;
    a4=(a2-a3);
    a4=(a0*a4);
    a4=(a1*a4);
    a4=(a0*a4);
    a2=(a2-a3);
    a2=(a0*a2);
    a2=(a1*a2);
    a2=(a0*a2);
    a4=(a4+a2);
    if (res[0]!=0) res[0][2]=a4;
    a4=arg[0]? arg[0][3] : 0;
    a2=arg[1]? arg[1][1] : 0;
    a3=(a4-a2);
    a3=(a0*a3);
    a3=(a1*a3);
    a3=(a0*a3);
    a4=(a4-a2);
    a4=(a0*a4);
    a1=(a1*a4);
    a0=(a0*a1);
    a3=(a3+a0);
    if (res[0]!=0) res[0][3]=a3;
    return 0;
}

int FORCESNLPsolver_objective1rd_30(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f5(arg, res, iw, w, mem);
}

const casadi_int* FORCESNLPsolver_objective1rd_30_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s4;
        default: return 0;
    }
}

#ifdef __cplusplus
} /* extern "C" */
#endif
