/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FORCESNLPsolver_casadi_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[14] = {1, 7, 0, 1, 2, 3, 4, 4, 4, 4, 0, 0, 0, 0};
static const casadi_int casadi_s5[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s6[31] = {5, 7, 0, 4, 8, 9, 10, 14, 17, 21, 0, 1, 2, 3, 0, 1, 3, 4, 0, 1, 0, 1, 2, 3, 0, 1, 3, 0, 1, 3, 4};
static const casadi_int casadi_s7[14] = {2, 7, 0, 0, 0, 2, 4, 4, 4, 4, 0, 1, 0, 1};

/* FORCESNLPsolver_objective_1:(i0[7],i1[2],i2[],i3[])->(o0,o1[1x7,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
    a0=100.;
    a1=arg[0]? arg[0][2] : 0;
    a2=fabs(a1);
    a2=(a0*a2);
    a3=arg[0]? arg[0][3] : 0;
    a4=4.;
    a3=(a3-a4);
    a4=fabs(a3);
    a4=(a0*a4);
    a2=(a2+a4);
    a4=1.0000000000000001e-001;
    a5=arg[0]? arg[0][0] : 0;
    a6=casadi_sq(a5);
    a6=(a4*a6);
    a2=(a2+a6);
    a6=1.0000000000000000e-002;
    a7=arg[0]? arg[0][1] : 0;
    a8=casadi_sq(a7);
    a8=(a6*a8);
    a2=(a2+a8);
    if (res[0]!=0) res[0][0]=a2;
    a5=(a5+a5);
    a4=(a4*a5);
    if (res[1]!=0) res[1][0]=a4;
    a7=(a7+a7);
    a6=(a6*a7);
    if (res[1]!=0) res[1][1]=a6;
    a1=casadi_sign(a1);
    a1=(a0*a1);
    if (res[1]!=0) res[1][2]=a1;
    a3=casadi_sign(a3);
    a0=(a0*a3);
    if (res[1]!=0) res[1][3]=a0;
    return 0;
}

int FORCESNLPsolver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f0(arg, res, iw, w, mem);
}

const casadi_int* FORCESNLPsolver_objective_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s3;
        case 1: return casadi_s4;
        default: return 0;
    }
}

/* FORCESNLPsolver_dynamics_1:(i0[7],i1[2],i2[],i3[])->(o0[5],o1[5x7,21nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a6, a7, a8, a9;
    a0=arg[0]? arg[0][2] : 0;
    a1=1.6666666666666666e-002;
    a2=arg[0]? arg[0][4] : 0;
    a3=arg[0]? arg[0][5] : 0;
    a4=5.0000000000000000e-001;
    a5=arg[0]? arg[0][6] : 0;
    a6=tan(a5);
    a6=(a4*a6);
    a7=atan(a6);
    a8=(a3+a7);
    a9=cos(a8);
    a10=(a2*a9);
    a11=2.;
    a12=5.0000000000000003e-002;
    a13=arg[0]? arg[0][0] : 0;
    a14=(a12*a13);
    a14=(a2+a14);
    a15=(a2/a4);
    a16=sin(a7);
    a17=(a15*a16);
    a18=(a12*a17);
    a18=(a3+a18);
    a19=arg[0]? arg[0][1] : 0;
    a20=(a12*a19);
    a20=(a5+a20);
    a21=tan(a20);
    a21=(a4*a21);
    a22=atan(a21);
    a23=(a18+a22);
    a24=cos(a23);
    a25=(a14*a24);
    a25=(a11*a25);
    a10=(a10+a25);
    a25=(a12*a13);
    a25=(a2+a25);
    a26=(a14/a4);
    a27=sin(a22);
    a28=(a26*a27);
    a29=(a12*a28);
    a29=(a3+a29);
    a30=(a12*a19);
    a30=(a5+a30);
    a31=tan(a30);
    a31=(a4*a31);
    a32=atan(a31);
    a33=(a29+a32);
    a34=cos(a33);
    a35=(a25*a34);
    a35=(a11*a35);
    a10=(a10+a35);
    a35=1.0000000000000001e-001;
    a36=(a35*a13);
    a36=(a2+a36);
    a37=(a25/a4);
    a38=sin(a32);
    a39=(a37*a38);
    a40=(a35*a39);
    a40=(a3+a40);
    a41=(a35*a19);
    a41=(a5+a41);
    a42=tan(a41);
    a42=(a4*a42);
    a43=atan(a42);
    a44=(a40+a43);
    a45=cos(a44);
    a46=(a36*a45);
    a10=(a10+a46);
    a10=(a1*a10);
    a0=(a0+a10);
    if (res[0]!=0) res[0][0]=a0;
    a0=arg[0]? arg[0][3] : 0;
    a10=(a3+a7);
    a46=sin(a10);
    a47=(a2*a46);
    a18=(a18+a22);
    a48=sin(a18);
    a49=(a14*a48);
    a49=(a11*a49);
    a47=(a47+a49);
    a29=(a29+a32);
    a49=sin(a29);
    a50=(a25*a49);
    a50=(a11*a50);
    a47=(a47+a50);
    a40=(a40+a43);
    a50=sin(a40);
    a51=(a36*a50);
    a47=(a47+a51);
    a47=(a1*a47);
    a0=(a0+a47);
    if (res[0]!=0) res[0][1]=a0;
    a0=(a11*a13);
    a0=(a13+a0);
    a47=(a11*a13);
    a0=(a0+a47);
    a0=(a0+a13);
    a0=(a1*a0);
    a0=(a2+a0);
    if (res[0]!=0) res[0][2]=a0;
    a28=(a11*a28);
    a17=(a17+a28);
    a39=(a11*a39);
    a17=(a17+a39);
    a39=(a36/a4);
    a28=sin(a43);
    a0=(a39*a28);
    a17=(a17+a0);
    a17=(a1*a17);
    a3=(a3+a17);
    if (res[0]!=0) res[0][3]=a3;
    a3=(a11*a19);
    a3=(a19+a3);
    a17=(a11*a19);
    a3=(a3+a17);
    a3=(a3+a19);
    a3=(a1*a3);
    a3=(a5+a3);
    if (res[0]!=0) res[0][4]=a3;
    a3=(a12*a24);
    a3=(a11*a3);
    a19=(a12*a34);
    a33=sin(a33);
    a17=(a35*a27);
    a0=(a12*a17);
    a13=(a33*a0);
    a13=(a25*a13);
    a19=(a19-a13);
    a19=(a11*a19);
    a3=(a3+a19);
    a19=(a35*a45);
    a44=sin(a44);
    a13=(a35*a38);
    a47=(a35*a13);
    a51=(a44*a47);
    a51=(a36*a51);
    a19=(a19-a51);
    a3=(a3+a19);
    a3=(a1*a3);
    if (res[1]!=0) res[1][0]=a3;
    a3=(a12*a48);
    a3=(a11*a3);
    a19=(a12*a49);
    a29=cos(a29);
    a0=(a29*a0);
    a0=(a25*a0);
    a19=(a19+a0);
    a19=(a11*a19);
    a3=(a3+a19);
    a19=(a35*a50);
    a40=cos(a40);
    a47=(a40*a47);
    a47=(a36*a47);
    a19=(a19+a47);
    a3=(a3+a19);
    a3=(a1*a3);
    if (res[1]!=0) res[1][1]=a3;
    if (res[1]!=0) res[1][2]=a35;
    a17=(a11*a17);
    a13=(a11*a13);
    a17=(a17+a13);
    a13=2.0000000000000001e-001;
    a13=(a13*a28);
    a17=(a17+a13);
    a17=(a1*a17);
    if (res[1]!=0) res[1][3]=a17;
    a23=sin(a23);
    a20=cos(a20);
    a20=casadi_sq(a20);
    a17=(a12/a20);
    a17=(a4*a17);
    a13=1.;
    a21=casadi_sq(a21);
    a21=(a13+a21);
    a17=(a17/a21);
    a3=(a23*a17);
    a3=(a14*a3);
    a3=(a11*a3);
    a22=cos(a22);
    a19=(a22*a17);
    a19=(a26*a19);
    a47=(a12*a19);
    a30=cos(a30);
    a30=casadi_sq(a30);
    a0=(a12/a30);
    a0=(a4*a0);
    a31=casadi_sq(a31);
    a31=(a13+a31);
    a0=(a0/a31);
    a51=(a47+a0);
    a51=(a33*a51);
    a51=(a25*a51);
    a51=(a11*a51);
    a3=(a3+a51);
    a32=cos(a32);
    a51=(a32*a0);
    a51=(a37*a51);
    a52=(a35*a51);
    a41=cos(a41);
    a41=casadi_sq(a41);
    a53=(a35/a41);
    a53=(a4*a53);
    a42=casadi_sq(a42);
    a42=(a13+a42);
    a53=(a53/a42);
    a54=(a52+a53);
    a54=(a44*a54);
    a54=(a36*a54);
    a3=(a3+a54);
    a3=(a1*a3);
    a3=(-a3);
    if (res[1]!=0) res[1][4]=a3;
    a18=cos(a18);
    a17=(a18*a17);
    a17=(a14*a17);
    a17=(a11*a17);
    a47=(a47+a0);
    a47=(a29*a47);
    a47=(a25*a47);
    a47=(a11*a47);
    a17=(a17+a47);
    a52=(a52+a53);
    a52=(a40*a52);
    a52=(a36*a52);
    a17=(a17+a52);
    a17=(a1*a17);
    if (res[1]!=0) res[1][5]=a17;
    a19=(a11*a19);
    a51=(a11*a51);
    a19=(a19+a51);
    a43=cos(a43);
    a53=(a43*a53);
    a53=(a39*a53);
    a19=(a19+a53);
    a19=(a1*a19);
    if (res[1]!=0) res[1][6]=a19;
    if (res[1]!=0) res[1][7]=a35;
    if (res[1]!=0) res[1][8]=a13;
    if (res[1]!=0) res[1][9]=a13;
    a16=(a11*a16);
    a19=(a12*a16);
    a53=(a23*a19);
    a53=(a14*a53);
    a24=(a24-a53);
    a24=(a11*a24);
    a9=(a9+a24);
    a27=(a11*a27);
    a24=(a12*a27);
    a53=(a33*a24);
    a53=(a25*a53);
    a34=(a34-a53);
    a34=(a11*a34);
    a9=(a9+a34);
    a38=(a11*a38);
    a34=(a35*a38);
    a53=(a44*a34);
    a53=(a36*a53);
    a45=(a45-a53);
    a9=(a9+a45);
    a9=(a1*a9);
    if (res[1]!=0) res[1][10]=a9;
    a19=(a18*a19);
    a19=(a14*a19);
    a48=(a48+a19);
    a48=(a11*a48);
    a46=(a46+a48);
    a24=(a29*a24);
    a24=(a25*a24);
    a49=(a49+a24);
    a49=(a11*a49);
    a46=(a46+a49);
    a34=(a40*a34);
    a34=(a36*a34);
    a50=(a50+a34);
    a46=(a46+a50);
    a46=(a1*a46);
    if (res[1]!=0) res[1][11]=a46;
    if (res[1]!=0) res[1][12]=a13;
    a27=(a11*a27);
    a16=(a16+a27);
    a38=(a11*a38);
    a16=(a16+a38);
    a28=(a11*a28);
    a16=(a16+a28);
    a16=(a1*a16);
    if (res[1]!=0) res[1][13]=a16;
    a8=sin(a8);
    a16=(a2*a8);
    a28=(a14*a23);
    a28=(a11*a28);
    a16=(a16+a28);
    a28=(a25*a33);
    a28=(a11*a28);
    a16=(a16+a28);
    a28=(a36*a44);
    a16=(a16+a28);
    a16=(a1*a16);
    a16=(-a16);
    if (res[1]!=0) res[1][14]=a16;
    a10=cos(a10);
    a16=(a2*a10);
    a28=(a14*a18);
    a28=(a11*a28);
    a16=(a16+a28);
    a28=(a25*a29);
    a28=(a11*a28);
    a16=(a16+a28);
    a28=(a36*a40);
    a16=(a16+a28);
    a16=(a1*a16);
    if (res[1]!=0) res[1][15]=a16;
    if (res[1]!=0) res[1][16]=a13;
    a5=cos(a5);
    a5=casadi_sq(a5);
    a5=(a4/a5);
    a6=casadi_sq(a6);
    a6=(a13+a6);
    a5=(a5/a6);
    a8=(a8*a5);
    a8=(a2*a8);
    a7=cos(a7);
    a7=(a7*a5);
    a15=(a15*a7);
    a7=(a12*a15);
    a20=(a4/a20);
    a20=(a20/a21);
    a21=(a7+a20);
    a23=(a23*a21);
    a23=(a14*a23);
    a23=(a11*a23);
    a8=(a8+a23);
    a22=(a22*a20);
    a26=(a26*a22);
    a12=(a12*a26);
    a30=(a4/a30);
    a30=(a30/a31);
    a31=(a12+a30);
    a33=(a33*a31);
    a33=(a25*a33);
    a33=(a11*a33);
    a8=(a8+a33);
    a32=(a32*a30);
    a37=(a37*a32);
    a35=(a35*a37);
    a4=(a4/a41);
    a4=(a4/a42);
    a42=(a35+a4);
    a44=(a44*a42);
    a44=(a36*a44);
    a8=(a8+a44);
    a8=(a1*a8);
    a8=(-a8);
    if (res[1]!=0) res[1][17]=a8;
    a10=(a10*a5);
    a2=(a2*a10);
    a7=(a7+a20);
    a18=(a18*a7);
    a14=(a14*a18);
    a14=(a11*a14);
    a2=(a2+a14);
    a12=(a12+a30);
    a29=(a29*a12);
    a25=(a25*a29);
    a25=(a11*a25);
    a2=(a2+a25);
    a35=(a35+a4);
    a40=(a40*a35);
    a36=(a36*a40);
    a2=(a2+a36);
    a2=(a1*a2);
    if (res[1]!=0) res[1][18]=a2;
    a26=(a11*a26);
    a15=(a15+a26);
    a11=(a11*a37);
    a15=(a15+a11);
    a43=(a43*a4);
    a39=(a39*a43);
    a15=(a15+a39);
    a1=(a1*a15);
    if (res[1]!=0) res[1][19]=a1;
    if (res[1]!=0) res[1][20]=a13;
    return 0;
}

int FORCESNLPsolver_dynamics_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f1(arg, res, iw, w, mem);
}

const casadi_int* FORCESNLPsolver_dynamics_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s5;
        case 1: return casadi_s6;
        default: return 0;
    }
}

/* FORCESNLPsolver_inequalities_1:(i0[7],i1[2],i2[],i3[])->(o0[2],o1[2x7,4nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
    a0=arg[0]? arg[0][2] : 0;
    a1=casadi_sq(a0);
    a2=arg[0]? arg[0][3] : 0;
    a3=casadi_sq(a2);
    a1=(a1+a3);
    if (res[0]!=0) res[0][0]=a1;
    a1=arg[1]? arg[1][0] : 0;
    a1=(a0-a1);
    a3=casadi_sq(a1);
    a4=arg[1]? arg[1][1] : 0;
    a4=(a2-a4);
    a5=casadi_sq(a4);
    a3=(a3+a5);
    if (res[0]!=0) res[0][1]=a3;
    a0=(a0+a0);
    if (res[1]!=0) res[1][0]=a0;
    a1=(a1+a1);
    if (res[1]!=0) res[1][1]=a1;
    a2=(a2+a2);
    if (res[1]!=0) res[1][2]=a2;
    a4=(a4+a4);
    if (res[1]!=0) res[1][3]=a4;
    return 0;
}

int FORCESNLPsolver_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f2(arg, res, iw, w, mem);
}

const casadi_int* FORCESNLPsolver_inequalities_1_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s1;
        case 1: return casadi_s7;
        default: return 0;
    }
}

/* FORCESNLPsolver_objective_50:(i0[7],i1[2],i2[],i3[])->(o0,o1[1x7,4nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
    a0=100.;
    a1=arg[0]? arg[0][2] : 0;
    a2=fabs(a1);
    a2=(a0*a2);
    a3=arg[0]? arg[0][3] : 0;
    a4=4.;
    a3=(a3-a4);
    a4=fabs(a3);
    a4=(a0*a4);
    a2=(a2+a4);
    a4=1.0000000000000001e-001;
    a5=arg[0]? arg[0][0] : 0;
    a6=casadi_sq(a5);
    a6=(a4*a6);
    a2=(a2+a6);
    a6=1.0000000000000000e-002;
    a7=arg[0]? arg[0][1] : 0;
    a8=casadi_sq(a7);
    a8=(a6*a8);
    a2=(a2+a8);
    if (res[0]!=0) res[0][0]=a2;
    a5=(a5+a5);
    a4=(a4*a5);
    if (res[1]!=0) res[1][0]=a4;
    a7=(a7+a7);
    a6=(a6*a7);
    if (res[1]!=0) res[1][1]=a6;
    a1=casadi_sign(a1);
    a1=(a0*a1);
    if (res[1]!=0) res[1][2]=a1;
    a3=casadi_sign(a3);
    a0=(a0*a3);
    if (res[1]!=0) res[1][3]=a0;
    return 0;
}

int FORCESNLPsolver_objective_50(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f3(arg, res, iw, w, mem);
}

const casadi_int* FORCESNLPsolver_objective_50_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s3;
        case 1: return casadi_s4;
        default: return 0;
    }
}

/* FORCESNLPsolver_inequalities_50:(i0[7],i1[2],i2[],i3[])->(o0[2],o1[2x7,4nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
    a0=arg[0]? arg[0][2] : 0;
    a1=casadi_sq(a0);
    a2=arg[0]? arg[0][3] : 0;
    a3=casadi_sq(a2);
    a1=(a1+a3);
    if (res[0]!=0) res[0][0]=a1;
    a1=arg[1]? arg[1][0] : 0;
    a1=(a0-a1);
    a3=casadi_sq(a1);
    a4=arg[1]? arg[1][1] : 0;
    a4=(a2-a4);
    a5=casadi_sq(a4);
    a3=(a3+a5);
    if (res[0]!=0) res[0][1]=a3;
    a0=(a0+a0);
    if (res[1]!=0) res[1][0]=a0;
    a1=(a1+a1);
    if (res[1]!=0) res[1][1]=a1;
    a2=(a2+a2);
    if (res[1]!=0) res[1][2]=a2;
    a4=(a4+a4);
    if (res[1]!=0) res[1][3]=a4;
    return 0;
}

int FORCESNLPsolver_inequalities_50(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f4(arg, res, iw, w, mem);
}

const casadi_int* FORCESNLPsolver_inequalities_50_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s1;
        case 1: return casadi_s7;
        default: return 0;
    }
}

#ifdef __cplusplus
} /* extern "C" */
#endif
