clear all;
clc;
clf
waypoints = [0,0,0; ... % Initial position
             0,10,0; ...
             1,10,0; ...
             1,0,0; ...
             0,0,0];    % Final position

toa = 0:4; % time of arrival

orientation = quaternion([0,0,0; ...
                          45,0,0; ...
                          135,0,0; ...
                          225,0,0; ...
                          0,0,0], ...
                          'eulerd','ZYX','frame');

% trajectory = waypointTrajectory(waypoints, ...
%     'TimeOfArrival',toa, ...
%     'Orientation',orientation, ...
%     'SampleRate',1);

               % Time, Waypoint, Orientation
trajectoryInfo = [0,   0,-5,0,   0,0,0; ... % Initial position
                  0.5, -0.5,-0.5,0,  0,0,0; ...
                  2, 1,6,0,  0,0,0; ...
                  2.3, 3,4,0,  0,0,0; ...
                  2.6,   5,5,0,    0,0,0; ...
                  2.9, 6,5,0,  0,0,0; ...
                  3.5, 10,5,0,  0,0,0; ...
                  4, 15,5,0,  0,0,0; ...
                  4.5, 12,3,0,  0,0,0; ...
                  5, 8,0,0,  0,0,0; ...
                  5.5, 11,-2,0,  0,0,0; ...
                  6, 10,-4,0,  0,0,0; ...
                  6.5, 11,-6,0,  0,0,0; ...
                  7, 9,-7,0,  0,0,0; ...
                  7.5, 6,-10,0,  0,0,0; ...
                  8, 3,-13,0,  0,0,0; ...
                  8.5, 0,-8,0,  0,0,0; ...
                  9,   0,-5,0,    180,0,0];    % Final position

trajectory = waypointTrajectory(trajectoryInfo(:,2:4), ...
    'TimeOfArrival',trajectoryInfo(:,1), ...
    'Orientation',quaternion(trajectoryInfo(:,5:end),'eulerd','ZYX','frame'), ...
    'SampleRate',100);
xpos =[];
ypos =[];

figure(1)
plot(trajectoryInfo(:,2),trajectoryInfo(:,3),'g.', 'MarkerSize', 10)
title('Position')
axis([-20,20,-20,20])
axis square
xlabel('X')
ylabel('Y')
grid on
hold on

orientationLog = zeros(toa(end)*trajectory.SampleRate,1,'quaternion');
count = 1;
while ~isDone(trajectory)
   [currentPosition,orientationLog(count)] = trajectory();
    
   plot(currentPosition(1),currentPosition(2),'bo')
   xpos = [xpos,currentPosition(1)];
   ypos = [ypos,currentPosition(2)];
   pause(trajectory.SamplesPerFrame/trajectory.SampleRate)
   count = count+1;
end
plot(trajectoryInfo(:,2),trajectoryInfo(:,3),'g.', 'MarkerSize', 10)
hold off
save('xpos.mat','xpos')
save('ypos.mat','ypos')

